index.bs

Just a few minor but important text edits

Adds a few important text edits that were discussed on today's workgroup call

---

index.bs

"maybe" should be "may be" in section 4.2 Session Layer
***
<a href="https://pr-preview.s3.amazonaws.com/polyphonic13/SIMID/pull/250.html" title="Last updated on May 14, 2019, 4:11 PM UTC (496d61a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/InteractiveAdvertisingBureau/SIMID/250/a18a438...polyphonic13:496d61a.html" title="Last updated on May 14, 2019, 4:11 PM UTC (496d61a)">Diff</a>

Grammar update

---

index.bs

This is the reverse of request full screen.
See issue: #251
***
<a href="https://pr-preview.s3.amazonaws.com/InteractiveAdvertisingBureau/SIMID/pull/263.html" title="Last updated on Jun 13, 2019, 4:44 PM UTC (30b57a6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/InteractiveAdvertisingBureau/SIMID/263/a18a438...30b57a6.html" title="Last updated on Jun 13, 2019, 4:44 PM UTC (30b57a6)">Diff</a>

Request exit full screen

---

index.bs

see issue #225
***
<a href="https://pr-preview.s3.amazonaws.com/InteractiveAdvertisingBureau/SIMID/pull/262.html" title="Last updated on Jun 13, 2019, 4:36 PM UTC (a9f20c2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/InteractiveAdvertisingBureau/SIMID/262/a18a438...a9f20c2.html" title="Last updated on Jun 13, 2019, 4:36 PM UTC (a9f20c2)">Diff</a>

Changes SIMID:Video:xyz to SIMID:Media:xyz

---

examples/creatives/base_simid_creative.js
examples/player/simid_player.js
examples/simid_protocol.js

1. Remove unneeded async message.
2. Changes VideoMessage to MediaMessage.
3. Change SIMID:Video:* to SIMID:Media:*

Updated samples

---

index.html

No changes just an update to the html.

Updated html doc with newest build

---

index.bs

1. Edited requestFullScreen language. 
2. Introduced` Creative:requestExitFullScreen` message.
***
<a href="https://pr-preview.s3.amazonaws.com/InteractiveAdvertisingBureau/SIMID/pull/259.html" title="Last updated on Jun 27, 2019, 6:16 PM UTC (1f181c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/InteractiveAdvertisingBureau/SIMID/259/a18a438...1f181c8.html" title="Last updated on Jun 27, 2019, 6:16 PM UTC (1f181c8)">Diff</a>

Full screen related messages editions

---

index.bs
index_TEMP.html

Shared the same CSS on all tables, added some cell padding, lightened the background colors and added a stroke.
***
<a href="https://pr-preview.s3.amazonaws.com/InteractiveAdvertisingBureau/SIMID/pull/276.html" title="Last updated on Jun 20, 2019, 7:49 AM UTC (6d51e9e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/InteractiveAdvertisingBureau/SIMID/276/adc4284...6d51e9e.html" title="Last updated on Jun 20, 2019, 7:49 AM UTC (6d51e9e)">Diff</a>

Restyled tables for improved readability

---

README.md
index.bs
index.html
simid-1.0.html

- Sets version to 1.0
- moves protocol message lower so as not to scare devs with hard to grok complexity
- creates a simid-1.0.html file to serve as versioned release in perpetuity
- Adds a link to that version to the main file.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jun 27, 2019, 11:47 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertisingBureau%2FSIMID%2F13847b3fe040a1f9a4 …

Version1 update

---

index.bs

***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Nov 8, 2019, 8:11 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertisingBureau%2FSIMID%2Fffc9f7fd64e6ef2df00bc72c3f40ecbde5cbb66a%2Findex.bs&md-warning=not%20ready)
```
FATAL ERROR: Line 1101 isn't indented enough (needs 1 indent) to be valid Markdown:
"  and that only those two parties …
```

Latest copy edits bulk

---

index.html

Ran the script to update html.

updated html only

---

index.html

updates html file

---

index.html

newest html version

---

index.bs

***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jun 10, 2020, 6:07 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertisingBureau%2FSIMID%2F007d206c06199039a315482300b30bd48b335ed9%2Findex.bs&md-warning=not%20ready)
```
"&lt;/div>"
✘  Did not generate, due to …
```

Enahnced Error Codes section copy

---

examples/ReadMe.txt

This changes the readme file for using the sample ads and player.
The old python 2 server will buffer on video, whereas the new server works better.

Add better local server call

---

README.md

Named versions are now bullet points with links.

Fixes the readme for named vesrions

---

examples/creatives/base_simid_creative.js
examples/creatives/simid_overlay.html
examples/creatives/simid_overlay.js
examples/player/simid_player.js
examples/simid_protocol.js

-Implemented log functionality which appears on spec but not in code

Added creativeMessage Log functionality.

---

examples/player/simid_player.js

-Updated the iframe attributes to allow geolocation needed for new sample creative

Allow geolocation in sample player iframe

---

examples/creatives/base_simid_creative.js

This allows users to override onInit and still have access to data changes.

Updated base creative onInit function

---

examples/creatives/testers_nonlinear.html

-Fix resizing inputs
-Added tool-kit
-Added translucent background to iframe

Css improvements

---

examples/creatives/testers_nonlinear.html

-Accidentally merged my cssImprovements with a different branch not master so just created a new branch

Resizing inputs improvements.

---

examples/creatives/testers_nonlinear.js
examples/player/simid_player.js

Fixed requestResize function to take in parameters that match those of the spec

Request resize

---

examples/player/simid_player.html
examples/player/simid_player.js

-remove comments in setControlState function parameter based on Ryan's PR comment

Remove param comments.

---

examples/creatives/base_simid_creative.js
examples/creatives/testers_nonlinear.js

--Update the base SIMID creative so that it keeps track of both the creative dimensions and the player dimensions
--Update the nonlinear creative to make proper resize function call based off of updates

Add dimension tracking to base creative

---

index.bs

Updates live version to version 1.1.0
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jul 30, 2020, 2:09 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertisingBureau%2FSIMID%2Fb93e698e236ed26cf8f7358e10c5088eb10eeee1%2Findex.bs&md-warning=not%20ready)
``` …
```

Update version number

---

examples/creatives/extender.js
examples/creatives/simid_overlay.html
examples/creatives/simid_overlay.js
examples/player/simid_player.html
examples/player/simid_player.js

-fixed bug that didn't allow a request duration to shorten the ad
-refactored request duration logic to deal with shortening the ad, extending the ad, and what happens if the creative requests a negative duration

Duration change bug

---

index.bs

A list of what's new in SIMID 1.1.0.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Aug 4, 2020, 8:24 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertisingBureau%2FSIMID%2Fc19c63dc8d67a052f1e15bfd903cbdf7bb0d12af%2Findex.bs&md-warning=not%20ready)
```
FATAL ERROR: Line 513 isn't indented enough (needs 1 indent) to be valid Markdown:
" …
```

Summary of 1.1.0 changes

---

index.bs

Changes to nonlinear sections for grammar improvements.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Aug 20, 2020, 3:21 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertisingBureau%2FSIMID%2Fd1632a86d48008bfe11bd6ff0d495f335cec5c99%2Findex.bs&md-warning=not%20ready)
```
FATAL ERROR: Line 513 isn't indented enough (needs 1 indent) to be …
```

Grammar changes

---

index.bs

Also corrected some grammar and made the errors more consistent.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Sep 3, 2020, 4:25 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertisingBureau%2FSIMID%2Fadc9cbc3bd2f1e5d92214069c636970503966cd5%2Findex.bs&md-warning=not%20ready)
```
FATAL ERROR: Line 513 isn't indented enough (needs 1 …
```

Update error descriptions

---

index.bs
index.html

This should read "reject" instead.
Also fixes Initilaizatioin to Initialization.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Feb 25, 2022, 6:21 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertisingBureau%2FSIMID%2F406d27d7795ae210936f0d2e5c6416c0bf4d8a70%2Findex.bs&md-warning=not%20ready)
```
FATAL ERROR: Line 513 isn't indented …
```

SIMID-236: Fix "resolve" typo in 8.2.2
