InteractiveAdvertisingBureau/SIMID

- index.bs
Specifies clearly that a player should error out if the ad requires variable duration but the player does not support it.
This is a redo of pr 87 as creating a new branch was quicker than updating that branch.
***
<a href="https://pr-preview.s3.amazonaws.com/InteractiveAdvertisingBureau/SIMID/pull/248.html" title="Last updated on May 9, 2019, 9:26 PM UTC (cd91b5a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/InteractiveAdvertisingBureau/SIMID/248/145fe15...cd91b5a.html" title="Last updated on May 9, 2019, 9:26 PM UTC (cd91b5a)">Diff</a>
> Clarifies behavior of variableDuraion

- index.bs
1. Introduced more timeout details.
1. Stopping video and hiding creative is mandatory.
1. Enforces adStopped message reporting **after** video is stopped and iframe becomes invisible.
1. Reads better.
***
<a href="https://pr-preview.s3.amazonaws.com/InteractiveAdvertisingBureau/SIMID/pull/260.html" title="Last updated on Jun 11, 2019, 3:57 PM UTC (683c6ee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/InteractiveAdvertisingBureau/SIMID/260/a18a438...683c6ee.html" title="Last updated on Jun 11, 2019, 3:57 PM UTC (683c6ee)">Diff</a>
> Edited SIMID:Player:adStopped language

- index.bs
1. Details of timeout introduced.
1. Video and creative hiding strictly enforced.
1. Clarified that adSkipped is reported **AFTER** video is stopped and iframe becomes invisible.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jun 11, 2019, 4:12 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertisingBureau%2FSIMID%2Fca7876539555197c2d4c806366a46faa3f8c253c%2Findex.bs&md-warning=not%20r …
> SIMID:Player:adSkipped enhancements

- index.bs
This update includes:
1. New messaging protocol section language.
1. Examples visualization enhancements.
1. CSS additions.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Feb 13, 2020, 5:20 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertisingBureau%2FSIMID%2F6ab7b6f8f6af767aeb5b06c4807aa2e37adeda5e%2Findex.bs&md-warning=not%20ready)
```
Error running preprocessor, returned code: …
```
> Messaging protocol and examples presentation updates

- index.bs
Changes:
1. Messaging protocol.
1. `Player:init` language and diagrams.
1. `Player:startCreative` language and diagrams.
1. Renamed backgrounding-related messages.
1. Changed fullscreen text uniformly.
1. Renamed `Creative:getVideoState` to `Creative:getMediaState`.
1. Added aggregated diagram to the section "6.1. How to Handle Ad Loading"
1. Minor CSS and copy chnages.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 2, 2020, 10:03 PM UTC)_.
<details>
:link: …
> Update index.bs with new copy

- index.bs
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 27, 2020, 2:18 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertisingBureau%2FSIMID%2F307be6e280280f9563c0dcddabdbf6f92b0a8385%2Findex.bs&md-warning=not%20ready)
```
"&lt;/div>"
✘  Did not generate, due to …
```
> Fixed incorrect play message when it should be playing

- index.bs
Grammar and such.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Apr 2, 2020, 2:15 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertisingBureau%2FSIMID%2Fb61c0268194f3f544f3c75e7311266e50b25ecec%2Findex.bs&md-warning=not%20ready)
```
"&lt;/div>"
✘  Did not …
```
> Aronschatz new fixes

- index.bs
1. A lot of diagram numbers did not sync with the numbers on the diagrams, so I referenced diagrams by their names.
2. I moved the start creative workflow to the workflow section and referenced it.
3. I broke up the additional notes sections in to paragraphs that made sense.
4. I added 2 new error messages and replaced the XXX place fillers with those message numbers.
5. I specified in the WARNING log message note, that these were messages for developers.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Apr 3, 2020, 5:10 PM UTC)_.
<details>
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) …
> Edits to 1.0.1

- index.bs
This is a simple typo fix.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Apr 27, 2020, 8:56 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertisingBureau%2FSIMID%2Fa50d86999d6b6c12db12f16e79b1c2c9d45b0dee%2Findex.bs&md-warning=not%20ready)
```
"&lt;/div>" …
```
> Fixed typo in ad completion cases

- index.bs
The notes section is restating things that are already stated in another section of the code.  So we've decided to remove it.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Apr 24, 2020, 2:53 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertisingBureau%2FSIMID%2F2497ed101a8e65791bd013dd4ed282b8797df51b%2Findex.bs&md-warning=not%20ready)
```
Error running preprocessor, returned code: …
```
> Remove notes section

- index.bs
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on May 28, 2020, 3:04 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertisingBureau%2FSIMID%2F00f317f69b244e721544d61a99e363f4dd61670a%2Findex.bs&md-warning=not%20ready)
```
"&lt;/div>"
✘  Did not generate, due to …
```
> Removed appBackgournded resolve response deprecation note

- examples/player/simid_player.js
The new workflow introduces 2 promises:
1. sessionCreatedPromise_ that resolves when the simid creative initializes a session.
2. resolveInitializationPromise_ that resolves when initialization is resolved.
The workflow should be:
1. Creative creates  a session.
2. Player calls SIMID:player:Init
3. Creative calls SIMID:Player:startCreative
However, these are all asynchronous so they may be called out of order. In order to keep these in order, this sample code uses promises.
Calling Init will 
1. wait for the session to be created (via sessionCreatedPromise_) 
2. then call SIMID:player:init
Calling playAd will:
1. Wait for the creative to respond to the initialization message (via resolveInitializationPromise_)
2. then call SIMID:player:startCreative
> Refactors promises to be more simple to read

- examples/player/simid_player.js
Previously when a creative responded with reject to an init message this would cause an error because we were not listening for a reject message immediately.
Also:
- Fixes a bug where the parameters of the reject message were not being passed through.
- Logs the parameters from the reject message.
> Fix init reject bug

- examples/player/simid_player.html
- examples/player/simid_player.js
- examples/simid_protocol.js
-Fixed bug where iframe listeners weren't being cleared properly so the iframe was considered null when it was actually initialized --> this problem created the error where you were unable to close and iframe, initialize a new one and close the second iframe because the functions would still try to close the first iframe the second time around
-Fixed the bug where the player buttons didn't disable when closing the ad from the creative
> X button bug

- index.bs
1214 | Environment does not support navigation. | The creative asked to open a navigation window, but the environment doesn’t support it. The creative should be opening the navigation window.
-- | -- | --
1215 | Navigation not possible at all on this device. | The creative asked for a navigation. However, navigation window opening is not possible at all on this device.
1216 | Too many calls to requestNavigation. | The creative asked for request navigation too many times and call will be blocked.
1217 | Invalid navigation request URL. | The creative requested navigation but the url was invalid.
1218 | Invalid navigation request app. | The creative requested a play store/app store url but that is not valid on this device.
1219 | Extra clickthrough blocked. | Clickthrough has been reported …
> Added new non linear error messages.

- index.bs
This is an information only API. It is exclusively for the player to tell the creative it will collapse it.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Aug 4, 2020, 7:15 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertisingBureau%2FSIMID%2Fb446484bc798d2c8cd904611fa461f776a299340%2Findex.bs&md-warning=not%20ready)
```
FATAL ERROR: …
```
> Adds SIMID:Player:collapse API

- index.bs
- index.html
Adds new optional init variable that lets the creative know if it should use requestNavigation or not.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Aug 5, 2020, 4:09 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertisingBureau%2FSIMID%2F1bb8f529dd8e5afb04be98a15967fac910daf74a%2Findex.bs&md-warning=not%20ready)
```
FATAL ERROR: Line …
```
> Updates init message

- index.bs
- index.html
As discussed last meeting I will be fixing 2 Issues.
https://github.com/InteractiveAdvertisingBureau/SIMID/issues/389
https://github.com/InteractiveAdvertisingBureau/SIMID/issues/382
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Aug 7, 2020, 7:14 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertisingBureau%2FSIMID%2Ff6ea2838fff13a118528a33a902fe287e768248e%2Findex.bs&md-warning=not% …
> Added duration to init and a new stop message

- index.bs
- index.html
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Aug 7, 2020, 7:52 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertisingBureau%2FSIMID%2F60357aa11599a121db4a4e3a543c3e821627e376%2Findex.bs&md-warning=not%20ready)
```
FATAL ERROR: Line 513 isn't indented enough (needs 1 indent) to be valid Markdown:
"  * New messages …
```
> adds docs for close buttons and navigation handling on clickthrough

- index.bs
1. Updated Creative:clickThru
2. Update diagrams images to align with conventions.
3. Update diagrams with descriptions.
4. Introduced a user experience diagram in Nonlinear Introduction section.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Aug 13, 2020, 4:58 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertisingBureau%2FSIMID%2Fa53b89555f7c70cf753cc58d8c9437c1269e9736%2Findex.bs&m …
> Updates and fixes

- examples/creatives/banner_nonlinear.js
- examples/creatives/testers_nonlinear.js
- examples/player/simid_player.js
- examples/simid_protocol.js
When we built the sample code we had not chosen the correct expand and collapse API names. This makes the sample consistent with the spec.
Pointed out by streiko
https://github.com/InteractiveAdvertisingBureau/SIMID/issues/406
> Rename expand and collapse to correct APIs

- index.bs
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Sep 3, 2020, 12:52 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertisingBureau%2FSIMID%2Fe1fe7c0f54d65278be8ee2859da2fe6a2e2da771%2Findex.bs&md-warning=not%20ready)
```
FATAL ERROR: Line 513 isn't indented enough (needs 1 indent) to be valid Markdown:
"  * New messages …
```
> Player:init skipoffset parameter and its description added

- index.bs
This is an error code a player can use if the creative doesn't create a session.
Some players might play the entire media before reporting this sort of an error, other players (like non linear players) might time out. 
https://github.com/InteractiveAdvertisingBureau/SIMID/issues/315
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Sep 3, 2020, 6:11 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInter …
> No session created error code

- index.bs
For video dimensions or creative dimensions, it is possible that initialize will be called, but the publisher or sdk that implements SIMID may not yet know the dimensions as it may not itself be fully initialized.
In this situation, it will send the simid creative -1.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Oct 28, 2020, 5:11 PM UTC)_.
<details>
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FInteractiveAdvertis …
> Negative 1 indicates unknown size

- examples/player/simid_player.js
I think there was a mistake in trackEventsOnAdVideoElement_ function for DURATION_CHANGE events
> changed event name and args in players.js for duration changed

- index.html
I was starting to make my planned changes, but just running the build script on index.bs from master updated index.html with style changes from https://api.csswg.org/bikeshed/. There are no actual content changes, just stylistic ones, including:
- Updates some styling for copyright and date.
- Replace heycam.github.io/webidl with webidl.spec.whatwg.org (since the site moved there)
- Add a space after § symbol
> Rebuild index.html style

- index.bs
- index.html
Majority of the Simid message parameters are using DOMString as a data type, for example, the parameters of [SIMID:Player:init](https://interactiveadvertisingbureau.github.io/SIMID/#simid-player-init).
There is one exception, which is the parameter of [SIMID:Creative:requestNavigation](https://interactiveadvertisingbureau.github.io/SIMID/#simid-creative-requestNavigation) and it is using string instead of DOMString.
As discussed, this was an oversight and it should be corrected to DOMString. Because on the web, string and DOMString are equivalent, this is not a breaking change.
> Change SIMID:Creative:requestNavigation uri type to DOMString.

- examples/simid_protocol.js
This still generates a v4 UUID, as before. I chose [crypto.getRandomValues](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues) over [crypto.randomUUID](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID) since it supports [much older browsers including IE](https://caniuse.com/getrandomvalues), and doesn't require a secure context (HTTPS or localhost).
#308
I'll update the spec to include notes about using a cryptographically secure method in a separate PR.
> SIMID-308: Update sample to use web.crypto for generating session IDs.
